version: '3.9'

services:

  auth:
    build: ./auth

    ports:
      - '3001:3001'

    depends_on:
      - auth-db
      - redis

    env_file:
      - ./auth/.env

    volumes:
      - ./auth:/app
      - /app/node_modules

  product:
    build: ./product

    ports:
      - '3002:3002'

    depends_on:
      - product-db
      - redis

    env_file:
      - ./product/.env

    volumes:
      - ./product:/app
      - /app/node_modules

  notification:
    build: ./notification

    ports:
      - '3003:3003'

    depends_on:
      - redis

    env_file:
      - ./notification/.env

    volumes:
      - ./notification:/app
      - /app/node_modules

  nginx:
    build: ./nginx

    ports:
      - '80:80'

    depends_on:
      - auth
      - product
      - notification

  auth-db:
    image: mongo

    ports:
      - '27017:27017'

    volumes:
      - auth-data:/data/db

  product-db:
    image: mongo

    ports:
      - '27018:27017'

    volumes:
      - product-data:/data/db

  redis:
    image: redis:7-alpine

    ports:
      - '6379:6379'

    volumes:
      - redis-data:/data

    command: redis-server --appendonly yes


volumes:
  auth-data:
  product-data:
  redis-data: