version: '3.9'

services:

  auth:
    build: ./auth

    ports:
      - '3001:3001'

    depends_on:
      - auth-db
      - redis
      - rabbitmq

    env_file:
      - ./auth/.env

    volumes:
      - ./auth:/app
      - /app/node_modules

  product:
    build: ./product

    ports:
      - '3002:3002'

    depends_on:
      - product-db
      - redis
      - rabbitmq

    env_file:
      - ./product/.env

    volumes:
      - ./product:/app
      - /app/node_modules

  notification:
    build: ./notification

    ports:
      - '3003:3003'

    depends_on:
      - redis
      - rabbitmq

    env_file:
      - ./notification/.env

    volumes:
      - ./notification:/app
      - /app/node_modules

  address:
    build: ./address

    ports:
      - '3004:3004'

    depends_on:
      - address-db
      - redis
      - rabbitmq

    env_file:
      - ./address/.env

    volumes:
      - ./address:/app
      - /app/node_modules

  nginx:
    build: ./nginx

    ports:
      - '80:80'

    depends_on:
      - auth
      - product
      - notification
      - address

  auth-db:
    image: mongo

    ports:
      - '27017:27017'

    volumes:
      - auth-data:/data/db

  product-db:
    image: mongo

    ports:
      - '27018:27017'

    volumes:
      - product-data:/data/db

  address-db:
    image: mongo

    ports:
      - '27019:27017'

    volumes:
      - address-data:/data/db

  redis:
    image: redis:7-alpine

    ports:
      - '6379:6379'

    volumes:
      - redis-data:/data

    command: redis-server --appendonly yes

  rabbitmq:
    image: rabbitmq:3-management-alpine

    ports:
      - '5672:5672'
      - '15672:15672'

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq


volumes:
  auth-data:
    name: nodejs-microservices_auth-data
  product-data:
    name: nodejs-microservices_product-data
  address-data:
    name: nodejs-microservices_address-data
  redis-data:
    name: nodejs-microservices_redis-data
  rabbitmq-data:
    name: nodejs-microservices_rabbitmq-data