version: '3.9'

services:

  auth:
    build: ./auth

    ports:
      - '3001:3001'

    depends_on:
      - auth-db
      - redis

    environment:
      PORT: 3001
      MONGO_URL: mongodb://auth-db:27017/authdb
      JWT_SECRET_ACCESS: dipronil_secret_key
      JWT_SECRET_REFRESH: dipronil_refresh_key
      REDIS_CLIENT_URL: redis://redis:6379

    volumes:
      - ./auth:/app
      - /app/node_modules

  product:
    build: ./product

    ports:
      - '3002:3002'

    depends_on:
      - product-db
      - redis

    environment:
      PORT: 3002
      JWT_SECRET: dipronil_secret_key
      MONGO_URL: mongodb://product-db:27017/productdb
      REDIS_CLIENT_URL: redis://redis:6379

    volumes:
      - ./product:/app
      - /app/node_modules

  nginx:
    build: ./nginx

    ports:
      - '80:80'

    depends_on:
      - auth
      - product

  auth-db:
    image: mongo

    ports:
      - '27017:27017'

    volumes:
      - auth-data:/data/db

  product-db:
    image: mongo

    ports:
      - '27018:27017'

    volumes:
      - product-data:/data/db

  redis:
    image: redis:7-alpine

    ports:
      - '6379:6379'

    volumes:
      - redis-data:/data

    command: redis-server --appendonly yes


volumes:
  auth-data:
  product-data:
  redis-data: