server {
    listen 80;

    location /auth/ {
        proxy_pass http://auth:3001/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Authorization $http_authorization;
    }

    # location = /posts/api/v1/post {

    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    #     proxy_pass http://product:3002/api/v1/product;
    # }

    location /products/ {

        auth_request /internal/auth/verify;

        auth_request_set $user_id $upstream_http_x_user_id;
        auth_request_set $user_email $upstream_http_x_user_email;
        auth_request_set $user_role $upstream_http_x_user_role;

        proxy_set_header X-User-Id $user_id;
        proxy_set_header X-User-Email $user_email;
        proxy_set_header X-User-Role $user_role;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_pass http://product:3002/;
    }

    location /notification/ {

        # auth_request /internal/auth/verify;

        # auth_request_set $user_id $upstream_http_x_user_id;
        # auth_request_set $user_email $upstream_http_x_user_email;
        # auth_request_set $user_role $upstream_http_x_user_role;

        # proxy_set_header X-User-Id $user_id;
        # proxy_set_header X-User-Email $user_email;
        # proxy_set_header X-User-Role $user_role;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_pass http://notification:3003/;
    }


    location = /internal/auth/verify {
        internal;

        proxy_pass http://auth:3001/api/v1/token/verify-token;
        

        proxy_pass_request_body off;
        proxy_set_header Content-Length "";

        proxy_set_header Authorization $http_authorization;

        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Original-Method $request_method;
    }


    error_page 401 = @json401error;

    location @json401error {
        default_type application/json;
        return 401 '{"success":false,"message":"Unauthorized from Nginx"}';
    }

    error_page 404 = @json404error;

    location @json404error {
        default_type application/json;
        return 404 '{"success":false,"message":"Page not found from Nginx"}';
    }

    error_page 500 = @json500error;

    location @json500error {
        default_type application/json;
        return 500 '{"success":false,"message":"Internal Server Error"}';
    }

    error_page 502 = @json502error;

    location @json502error {
        default_type application/json;
        return 502 '{"success":false,"message":"Bad Gateway"}';
    }
}